apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mastercard
    domain: sd
    service: mastercard
  name: mastercard-sd-deployment
  namespace: sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastercard
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mastercard
        domain: sd
        service: mastercard
      namespace: sd
    spec:
      containers:
      - name: mastercard
        image: luizmartendal/mastercard-sd
        ports:
        - containerPort: 8901
      nodeSelector:
        domain: sd
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: domain
        operator: Equal
        value: sd

