@startuml include
!include ./CameraPerspective.puml
!include ./Utilitario.puml
!include ./Transformacao4D.puml
!include ./BBox.puml
!include ./Ponto4D.puml
!include ./Matematica.puml
!include ./Shaders/Shader.puml
!include ./Shaders/Texture.puml
@enduml
